-- Yasmine Service Management & Order Routing (Everest)
-- Run in Supabase SQL editor after prior migrations.

-- 1) Vendors (1:1 with public.users.id for role = vendor)
create table if not exists public.vendors (
  id text primary key,
  service_status text not null default 'away'
    check (service_status in ('active', 'away', 'scheduled_break')),
  weekly_schedule jsonb not null default '{}'::jsonb,
  last_active_at timestamptz,
  consecutive_timeout_orders integer not null default 0,
  updated_at timestamptz not null default now()
);

comment on table public.vendors is 'Everest vendor service state; id matches users.id (text).';
comment on column public.vendors.service_status is 'active = in service; away = out; scheduled_break = paused window';
comment on column public.vendors.weekly_schedule is '7-day keys e.g. mon..sun with {open,close} or {closed:true}';

-- 2) Products: SKU DNA = parent_sku + color_id + size_id (stored concatenated in sku_dna)
alter table public.products
  add column if not exists parent_sku text,
  add column if not exists variant_id text,
  add column if not exists color_id text,
  add column if not exists size_id text,
  add column if not exists sku_dna text;

create index if not exists idx_products_sku_dna on public.products (sku_dna);
create index if not exists idx_products_vendor_sku_dna on public.products (vendor_id, sku_dna);

-- 3) Orders: vendor + Yasmine routing metadata
alter table public.orders
  add column if not exists vendor_id text;

alter table public.orders
  add column if not exists yasmine_routing_status text,
  add column if not exists acceptance_deadline_at timestamptz,
  add column if not exists original_vendor_id text,
  add column if not exists estimated_ready_at timestamptz,
  add column if not exists yasmine_meta jsonb;

comment on column public.orders.yasmine_routing_status is 'pending_acceptance | rerouted | preorder | accepted | null';

-- 4) Admin alerts (timeouts, auto-away)
create table if not exists public.admin_alerts (
  id bigint generated by default as identity primary key,
  kind text not null,
  message text not null,
  meta jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_alerts_created on public.admin_alerts (created_at desc);

-- 5) Grants (demo-style anon, matches existing Everest migrations)
grant select, insert, update on table public.vendors to anon, authenticated;
grant usage, select on sequence public.admin_alerts_id_seq to anon, authenticated;
grant select, insert on table public.admin_alerts to anon, authenticated;

alter table public.vendors enable row level security;
alter table public.admin_alerts enable row level security;

drop policy if exists "vendors_anon_all_v1" on public.vendors;
create policy "vendors_anon_all_v1"
on public.vendors for all to anon, authenticated
using (true) with check (true);

drop policy if exists "admin_alerts_insert_v1" on public.admin_alerts;
create policy "admin_alerts_insert_v1"
on public.admin_alerts for insert to anon, authenticated
with check (true);

drop policy if exists "admin_alerts_select_v1" on public.admin_alerts;
create policy "admin_alerts_select_v1"
on public.admin_alerts for select to anon, authenticated
using (true);

notify pgrst, 'reload schema';
