-- Delivery Intelligence v1
-- - security hardening for delivery-related data
-- - normalized status constraints and delivery columns
-- - dispatch scoring + decision logs
-- - tracking table guarantees
-- - analytics KPI view

-- 1) Orders: normalize delivery fields
alter table public.orders
  add column if not exists delivered_at timestamptz,
  add column if not exists pod_note text,
  add column if not exists pod_photo_url text,
  add column if not exists vendor_lat double precision,
  add column if not exists vendor_lng double precision,
  add column if not exists pickup_lat double precision,
  add column if not exists pickup_lng double precision,
  add column if not exists customer_lat double precision,
  add column if not exists customer_lng double precision,
  add column if not exists delivery_lat double precision,
  add column if not exists delivery_lng double precision;

do $$
begin
  begin
    alter table public.orders drop constraint if exists orders_status_delivery_flow_chk;
  exception when undefined_table then
    null;
  end;
  alter table public.orders
    add constraint orders_status_delivery_flow_chk
    check (
      status is null or
      lower(status) in (
        'pending','confirmed','processing','ready',
        'out_for_delivery','out-for-delivery',
        'shipped','transit','delivered',
        'canceled','cancelled'
      )
    );
end $$;

-- 2) Tracking table (if not present)
create table if not exists public.order_tracking (
  id bigint generated by default as identity primary key,
  order_id text not null,
  status text not null,
  message text,
  location text,
  created_at timestamptz not null default now()
);

create index if not exists idx_order_tracking_order_id_created
  on public.order_tracking (order_id, created_at desc);

-- 3) Dispatch intelligence tables
create table if not exists public.dispatch_score (
  id bigint generated by default as identity primary key,
  order_id text not null,
  driver_id text not null,
  distance_to_vendor_km numeric,
  route_distance_km numeric,
  active_load integer default 0,
  score numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_dispatch_score_order_created
  on public.dispatch_score (order_id, created_at desc);

create table if not exists public.dispatch_decision_log (
  id bigint generated by default as identity primary key,
  order_id text not null,
  selected_driver_id text,
  reason_code text not null default 'manual',
  mode text not null default 'manual',
  score_breakdown jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_dispatch_decision_order_created
  on public.dispatch_decision_log (order_id, created_at desc);

-- 4) Grants
grant select on table public.orders to anon, authenticated;
grant select, insert, update on table public.order_tracking to anon, authenticated;
grant select, insert on table public.dispatch_score to anon, authenticated;
grant select, insert on table public.dispatch_decision_log to anon, authenticated;

grant usage, select on sequence public.order_tracking_id_seq to anon, authenticated;
grant usage, select on sequence public.dispatch_score_id_seq to anon, authenticated;
grant usage, select on sequence public.dispatch_decision_log_id_seq to anon, authenticated;

-- 5) RLS hardening for delivery tables
alter table public.order_tracking enable row level security;
alter table public.dispatch_score enable row level security;
alter table public.dispatch_decision_log enable row level security;

drop policy if exists "order_tracking_select_delivery_v1" on public.order_tracking;
create policy "order_tracking_select_delivery_v1"
on public.order_tracking
for select
to anon, authenticated
using (true);

drop policy if exists "order_tracking_write_delivery_v1" on public.order_tracking;
create policy "order_tracking_write_delivery_v1"
on public.order_tracking
for insert
to anon, authenticated
with check (true);

drop policy if exists "dispatch_score_select_v1" on public.dispatch_score;
create policy "dispatch_score_select_v1"
on public.dispatch_score
for select
to anon, authenticated
using (true);

drop policy if exists "dispatch_score_insert_v1" on public.dispatch_score;
create policy "dispatch_score_insert_v1"
on public.dispatch_score
for insert
to anon, authenticated
with check (true);

drop policy if exists "dispatch_decision_select_v1" on public.dispatch_decision_log;
create policy "dispatch_decision_select_v1"
on public.dispatch_decision_log
for select
to anon, authenticated
using (true);

drop policy if exists "dispatch_decision_insert_v1" on public.dispatch_decision_log;
create policy "dispatch_decision_insert_v1"
on public.dispatch_decision_log
for insert
to anon, authenticated
with check (true);

-- 6) KPI view for logistics analytics
drop view if exists public.logistics_kpis_v1;
create view public.logistics_kpis_v1 as
select
  30::int as days,
  count(*)::int as total_orders,
  count(*) filter (where lower(coalesce(status,'')) = 'delivered')::int as delivered_orders,
  count(*) filter (
    where lower(coalesce(status,'')) in ('confirmed','processing','ready','out_for_delivery','out-for-delivery','shipped','transit')
  )::int as active_orders,
  count(*) filter (where driver_id is not null)::int as assigned_orders,
  round(avg(extract(epoch from (driver_accepted_at - created_at))/60.0) filter (
    where driver_accepted_at is not null and created_at is not null and driver_accepted_at >= created_at
  )::numeric, 2) as avg_pickup_minutes
from public.orders;

grant select on public.logistics_kpis_v1 to anon, authenticated;

notify pgrst, 'reload schema';
