-- Everest Customer Service chat
-- Shared backend store for customer <-> Everest staff support messages.

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  thread_id text not null,
  client_id text not null,
  client_label text,
  client_email text,
  client_role text,
  is_guest boolean not null default false,
  from_side text not null check (from_side in ('user', 'staff')),
  body text not null default '',
  image_url text,
  staff_name text,
  local_id text,
  created_at timestamptz not null default now()
);

-- Allow message-only-with-image rows: relax the not null on body via default,
-- but keep at least one of body/image_url filled.
alter table public.support_messages
  add constraint support_messages_has_content
  check (length(coalesce(body, '')) > 0 or length(coalesce(image_url, '')) > 0);

create index if not exists idx_support_messages_thread_created
  on public.support_messages (thread_id, created_at asc);

create index if not exists idx_support_messages_created
  on public.support_messages (created_at desc);

create unique index if not exists idx_support_messages_local_id
  on public.support_messages (local_id)
  where local_id is not null;

grant usage, select on sequence public.support_messages_id_seq to anon, authenticated;
grant select, insert on table public.support_messages to anon, authenticated;

alter table public.support_messages enable row level security;

drop policy if exists "support_messages_insert_v1" on public.support_messages;
create policy "support_messages_insert_v1"
on public.support_messages for insert to anon, authenticated
with check (true);

drop policy if exists "support_messages_select_v1" on public.support_messages;
create policy "support_messages_select_v1"
on public.support_messages for select to anon, authenticated
using (true);

notify pgrst, 'reload schema';
