-- Product feedback system: ratings + comments persisted in Supabase.
-- Run in Supabase SQL editor (or via migration runner).

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id text not null,
  user_id text not null,
  user_name text not null default 'Customer',
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null check (length(trim(comment)) >= 3),
  created_at timestamptz not null default now()
);

create unique index if not exists uq_product_reviews_product_user
  on public.product_reviews (product_id, user_id);

create index if not exists idx_product_reviews_product
  on public.product_reviews (product_id);

grant select, insert, update, delete on table public.product_reviews to anon;
grant select, insert, update, delete on table public.product_reviews to authenticated;
grant usage, select on sequence public.product_reviews_id_seq to anon, authenticated;

alter table public.product_reviews enable row level security;

drop policy if exists "product_reviews_anon_select_demo" on public.product_reviews;
create policy "product_reviews_anon_select_demo"
on public.product_reviews
for select
to anon, authenticated
using (true);

drop policy if exists "product_reviews_anon_insert_demo" on public.product_reviews;
create policy "product_reviews_anon_insert_demo"
on public.product_reviews
for insert
to anon, authenticated
with check (true);

drop policy if exists "product_reviews_anon_update_demo" on public.product_reviews;
create policy "product_reviews_anon_update_demo"
on public.product_reviews
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "product_reviews_anon_delete_demo" on public.product_reviews;
create policy "product_reviews_anon_delete_demo"
on public.product_reviews
for delete
to anon, authenticated
using (true);

notify pgrst, 'reload schema';
